import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import { chromium } from '../../input_data/node_modules/playwright/index.mjs';

const inputRoot=process.cwd();
const outputRoot=path.resolve(inputRoot,'..','output');
const reportRoot=path.join(outputRoot,'reports');
const screenshotRoot=path.join(outputRoot,'evidence','screenshots');
const cases=JSON.parse(await fs.readFile(path.join(inputRoot,'fixtures','concurrent_link_cases.json'),'utf8'));
const contract=JSON.parse(await fs.readFile(path.join(inputRoot,'rules','concurrent_link_contract.json'),'utf8'));
const consoleHtml=await fs.readFile(path.join(inputRoot,'app','link_console.html'),'utf8');
const providerHtml=await fs.readFile(path.join(inputRoot,'app','provider.html'),'utf8');
const assert=(value,message)=>{if(!value)throw new Error(message)};
function csvCell(value){const text=String(value??'');return /[",\n]/u.test(text)?`"${text.replaceAll('"','""')}"`:text}
function toCsv(headers,rows){return `${headers.join(',')}\n${rows.map(row=>headers.map(header=>csvCell(row[header])).join(',')).join('\n')}\n`}
function origin(server){const address=server.address();return `http://127.0.0.1:${address.port}`}
function startServer(handler){const server=http.createServer(handler);return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolve(server))})}
function closeServer(server){return new Promise(resolve=>server.close(resolve))}
function respondJson(response,status,payload){const body=JSON.stringify(payload);response.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store'});response.end(body)}
async function readBody(request){const chunks=[];for await(const chunk of request)chunks.push(chunk);return Buffer.concat(chunks).toString('utf8')}

assert(Array.isArray(cases)&&cases.length>0,'场景合同为空');
assert(new Set(cases.map(item=>item.scenario_id)).size===cases.length,'scenario_id重复');
assert(Array.isArray(contract.slots)&&contract.slots.length===2,'槽位合同无效');
await fs.rm(reportRoot,{recursive:true,force:true});await fs.rm(path.join(outputRoot,'evidence'),{recursive:true,force:true});await fs.mkdir(reportRoot,{recursive:true});await fs.mkdir(screenshotRoot,{recursive:true});

const requests=[];let requestIndex=0;
const consoleServer=await startServer(async(request,response)=>{const url=new URL(request.url,'http://127.0.0.1');if(request.method==='POST'&&url.pathname===contract.confirmation_path){try{const payload=JSON.parse(await readBody(request));requestIndex+=1;const row={scenario_id:String(payload.scenario_id||''),request_index:requestIndex,slot:String(payload.slot||''),state:String(payload.state||''),authorization_code:String(payload.authorization_code||''),http_status:200};requests.push(row);respondJson(response,200,{accepted:true});return}catch{respondJson(response,400,{accepted:false});return}}if(url.pathname==='/link_console.html'){response.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});response.end(consoleHtml);return}response.writeHead(404);response.end()});
const trustedServer=await startServer((request,response)=>{if(new URL(request.url,'http://127.0.0.1').pathname==='/provider.html'){response.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});response.end(providerHtml);return}response.writeHead(404);response.end()});
const intruderServer=await startServer((request,response)=>{if(new URL(request.url,'http://127.0.0.1').pathname==='/provider.html'){response.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});response.end(providerHtml);return}response.writeHead(404);response.end()});
const consoleOrigin=origin(consoleServer);const trustedOrigin=origin(trustedServer);const intruderOrigin=origin(intruderServer);
const launchOptions=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{headless:true,channel:process.env.PW_CHANNEL||'chrome'};
const browser=await chromium.launch(launchOptions);const sessionRows=[];const eventRows=[];const slotRows=[];
try{
  for(const item of cases){
    const context=await browser.newContext({viewport:{width:1080,height:760}});const page=await context.newPage();const url=new URL('/link_console.html',consoleOrigin);for(const [key,value] of Object.entries({scenario_id:item.scenario_id,billing_state:item.states.billing,support_state:item.states.support,trusted_origin:trustedOrigin,provider_url:`${trustedOrigin}/provider.html`,message_type:contract.message_type,confirmation_path:contract.confirmation_path,timeout_ms:contract.slot_timeout_ms}))url.searchParams.set(key,String(value));await page.goto(url.toString());await page.waitForFunction(()=>window.__ready===true);
    const current=new Map();const previous=new Map();let intruder=null;
    for(const action of item.actions){
      if(action.op==='open'){const popupPromise=context.waitForEvent('page');await page.getByRole('button',{name:action.slot==='billing'?'绑定账单账号':'绑定客服账号'}).click();const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');current.set(action.slot,popup);continue}
      if(action.op==='retry'){const popupPromise=context.waitForEvent('page');previous.set(action.slot,current.get(action.slot));await page.evaluate(({slot,state,provider})=>window.__startSlot(slot,state,provider),{slot:action.slot,state:action.state,provider:`${trustedOrigin}/provider.html`});const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');current.set(action.slot,popup);continue}
      if(action.op==='open_intruder'){const popupPromise=context.waitForEvent('page');await page.evaluate(provider=>window.open(provider,'untrusted-provider','width=540,height=520'),`${intruderOrigin}/provider.html`);intruder=await popupPromise;await intruder.waitForLoadState('domcontentloaded');continue}
      if(action.op==='message'){const sender=action.from==='intruder'?intruder:action.from.endsWith('_previous')?previous.get(action.from.replace('_previous','')):current.get(action.from);assert(sender,`消息发送窗口不存在:${action.from}`);const state=action.state??item.states[action.state_from];await sender.evaluate(({payload,targetOrigin})=>window.opener.postMessage(payload,targetOrigin),{payload:{type:contract.message_type,slot:action.target,state,result:action.result,code:action.code},targetOrigin:consoleOrigin});await page.waitForTimeout(45);continue}
      if(action.op==='close'){const sender=current.get(action.slot);assert(sender,`关闭窗口不存在:${action.slot}`);await sender.close();await page.waitForFunction(slot=>window.__snapshot().slots[slot].status==='user_closed',action.slot);continue}
      throw new Error(`不支持的动作:${action.op}`);
    }
    await page.waitForFunction(()=>window.__terminal===true,null,{timeout:4000});await page.waitForFunction(()=>Object.values(window.__snapshot().slots).every(slot=>slot.popup_closed),null,{timeout:1000});const snapshot=await page.evaluate(()=>window.__snapshot());const caseRequests=requests.filter(row=>row.scenario_id===item.scenario_id);const accepted=snapshot.audit.filter(row=>row.decision==='accepted').length;const rejected=snapshot.audit.filter(row=>row.decision==='rejected').length;const passed=snapshot.slots.billing.status===item.expected.billing_status&&snapshot.slots.support.status===item.expected.support_status&&snapshot.audit.length===item.expected.events&&accepted===item.expected.accepted&&rejected===item.expected.rejected&&caseRequests.length===item.expected.requests;
    sessionRows.push({scenario_id:item.scenario_id,billing_status:snapshot.slots.billing.status,support_status:snapshot.slots.support.status,event_count:snapshot.audit.length,accepted_events:accepted,rejected_events:rejected,confirmation_requests:caseRequests.length,passed:String(passed)});
    snapshot.audit.forEach((row,index)=>eventRows.push({scenario_id:item.scenario_id,event_index:index+1,target_slot:row.target_slot,origin_class:row.origin_class,source_match:String(row.source_match),type_match:String(row.type_match),state_match:String(row.state_match),received_state:row.received_state,received_code:row.received_code,result:row.result,decision:row.decision,reason:row.reason}));
    for(const slot of contract.slots){const value=snapshot.slots[slot];slotRows.push({scenario_id:item.scenario_id,slot,generation:value.generation,state:value.state,status:value.status,popup_closed:String(value.popup_closed),request_count:value.request_count})}
    await page.screenshot({path:path.join(screenshotRoot,`${item.scenario_id}.png`),fullPage:true});await context.close();
  }
}finally{await browser.close();await closeServer(consoleServer);await closeServer(trustedServer);await closeServer(intruderServer)}

const controls={scenario_count:cases.length,slot_snapshot_rows:slotRows.length,event_rows:eventRows.length,accepted_events:eventRows.filter(row=>row.decision==='accepted').length,rejected_events:eventRows.filter(row=>row.decision==='rejected').length,confirmation_requests:requests.length,authorized_slots:slotRows.filter(row=>row.status==='authorized').length,canceled_slots:slotRows.filter(row=>row.status==='canceled').length,user_closed_slots:slotRows.filter(row=>row.status==='user_closed').length,timed_out_slots:slotRows.filter(row=>row.status==='timed_out').length,retry_generation_slots:slotRows.filter(row=>row.generation===2).length,screenshot_count:(await fs.readdir(screenshotRoot)).filter(name=>name.endsWith('.png')).length};
const expectedTotals=cases.reduce((sum,item)=>({events:sum.events+item.expected.events,accepted:sum.accepted+item.expected.accepted,rejected:sum.rejected+item.expected.rejected,requests:sum.requests+item.expected.requests}),{events:0,accepted:0,rejected:0,requests:0});
const invariants={all_scenarios_pass:sessionRows.every(row=>row.passed==='true'),two_slots_per_scenario:controls.slot_snapshot_rows===controls.scenario_count*2,event_total_matches_contract:controls.event_rows===expectedTotals.events,accepted_total_matches_contract:controls.accepted_events===expectedTotals.accepted,rejected_total_matches_contract:controls.rejected_events===expectedTotals.rejected,request_total_matches_contract:controls.confirmation_requests===expectedTotals.requests,confirmation_state_matches:requests.every(row=>slotRows.some(slot=>slot.scenario_id===row.scenario_id&&slot.slot===row.slot&&slot.state===row.state)),no_rejected_code_confirmed:eventRows.filter(event=>event.decision==='rejected'&&event.received_code).every(event=>!requests.some(request=>request.authorization_code===event.received_code)),source_rejection_observed:eventRows.some(row=>row.reason==='wrong_popup_source'),origin_rejection_observed:eventRows.some(row=>row.reason==='untrusted_origin'),retry_generation_observed:controls.retry_generation_slots===1,terminal_partition:controls.authorized_slots+controls.canceled_slots+controls.user_closed_slots+controls.timed_out_slots===controls.slot_snapshot_rows,evidence_per_scenario:controls.screenshot_count===controls.scenario_count,primary_keys_unique:new Set(sessionRows.map(row=>row.scenario_id)).size===sessionRows.length&&new Set(eventRows.map(row=>`${row.scenario_id}:${row.event_index}`)).size===eventRows.length&&new Set(slotRows.map(row=>`${row.scenario_id}:${row.slot}`)).size===slotRows.length};
controls.control_error_count=Object.values(invariants).filter(value=>value!==true).length;const control={result:controls.control_error_count===0?'PASS':'FAIL',controls,invariants};
await fs.writeFile(path.join(reportRoot,'session_results.csv'),toCsv(['scenario_id','billing_status','support_status','event_count','accepted_events','rejected_events','confirmation_requests','passed'],sessionRows));await fs.writeFile(path.join(reportRoot,'event_timeline.csv'),toCsv(['scenario_id','event_index','target_slot','origin_class','source_match','type_match','state_match','received_state','received_code','result','decision','reason'],eventRows));await fs.writeFile(path.join(reportRoot,'link_requests.csv'),toCsv(['scenario_id','request_index','slot','state','authorization_code','http_status'],requests));await fs.writeFile(path.join(reportRoot,'slot_snapshot.csv'),toCsv(['scenario_id','slot','generation','state','status','popup_closed','request_count'],slotRows));await fs.writeFile(path.join(reportRoot,'link_control.json'),`${JSON.stringify(control,null,2)}\n`);if(control.result!=='PASS')process.exitCode=2;
